apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phobos-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: {{ printf "%s(/|$)(.*)" .Values.mfe.path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: phobos-auth-service
                port:
                  number: 80