apiVersion: v1
kind: Service
metadata:
  name: phobos-auth-service
  labels:
    type: mfe
    name: phobos-auth
spec:
  selector:
    app: phobos-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000